# ╔══════════════════════════════════════════════╗
# ║                Configuration                 ║
# ╚══════════════════════════════════════════════╝
spring.application.name=library
application.cors=http://localhost:5173

forgepack.cache.ttl=1h
forgepack.cache.maximum-size=5000
forgepack.cache.initial-capacity=100