# ╔══════════════════════════════════════════════╗
# ║                Configuration                 ║
# ╚══════════════════════════════════════════════╝
spring.application.name=library
application.cors=http://localhost:5173